version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y maven
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
  reports:
    arn:aws:codebuild:us-east-1:939130155633:report-group/Cucumber-HTML-Reports:
    files:
      - '**/*'
    base-directory: 'target/cucumber-reports/advanced-reports/cucumber-html-reports/'

